Datura-ai/lium-io

neurons/miners/docker-compose.app.yml
neurons/validators/docker-compose.app.yml

• Removed exposing ports for redis at validator 
• Removed exposing ports for redis at miner

remove exposing ports for redis

---

neurons/executor/pdm.lock
neurons/executor/pyproject.toml
neurons/validators/pdm.lock
neurons/validators/pyproject.toml
neurons/validators/src/miner_jobs/machine_scrape.py

DAH-514
[Subnet - Utilization Info In Machine Spec](https://www.notion.so/8624050fd1ba4363be433dc457b3aa9b?v=f4338cc3f6424eff8315111a8e24f0e3&p=129b8bfdbde980ff88a9f5639f0eb316&pm=s)

add gpu, cpu, memory and disk utilization

---

neurons/validators/src/clients/miner_client.py
neurons/validators/src/services/miner_service.py
neurons/validators/src/services/task_service.py

• Removed unnecessary logs on validator(miner_client.py, miner_service.py, task_service.py)

remove the unnecessary  logs on validator

---

neurons/validators/src/services/docker_service.py
neurons/validators/src/services/task_service.py

- Reduce validator logs for machine spec

clean(validator): reduce unnecessary logs

---

.github/workflows/miner_cd_prod.yml

• Create CI/CD workflow for miner

feat(miner): DAH-597 CI/CD for miner

---

.github/workflows/executor_cd_prod.yml

• Create CI/CD workflow for executor

feat(executor): DAH-597 CI/CD for executor

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/clients/miner_client.py

logs update

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/clients/miner_client.py

hotfix: update miner_client logs

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/clients/miner_client.py
neurons/validators/src/services/task_service.py

hotfix: update task_service log

---

neurons/executor/Dockerfile
neurons/executor/Dockerfile.runner
neurons/validators/src/services/task_service.py

update validator task_service log and deploy executor

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/miner_jobs/machine_scrape.py
neurons/validators/src/miner_jobs/score.py
neurons/validators/src/services/const.py
neurons/validators/src/services/task_service.py

fix: cheating machine spec

---

neurons/executor/Dockerfile
neurons/executor/Dockerfile.runner
neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/clients/miner_client.py
neurons/validators/src/services/task_service.py

deploy validator

---

neurons/validators/.gitignore
neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/pdm.lock
neurons/validators/pyproject.toml
neurons/validators/src/cli.py
neurons/validators/src/miner_jobs/machine_scrape.py
neurons/validators/src/miner_jobs/score.py
neurons/validators/src/services/miner_service.py
neurons/validators/src/services/ssh_service.py
neurons/validators/src/services/task_service.py

- added pyarmor for obfuscating
- encoding/decoding the job result
DAH-638
[Subnet - fix hacking machine_scrap script on validator.](https://www.notion.so/8624050fd1ba4363be433dc457b3aa9b?v=f4338cc3f6424eff8315111a8e24f0e3&p=13bb8bfdbde9801e8247c09536e7a303&pm=s)

fix(validator): hacking ssh issue

---

neurons/validators/src/miner_jobs/machine_scrape.py
neurons/validators/src/miner_jobs/score.py

fix: preventing set the LD_PRELOAD so file

---

neurons/executor/Dockerfile
neurons/executor/Dockerfile.runner
neurons/executor/docker-compose.yml
neurons/miners/docker-compose.yml
neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/docker-compose.yml
neurons/validators/src/cli.py
neurons/validators/src/core/validator.py
neurons/validators/src/services/docker_service.py
neurons/validators/src/services/miner_service.py
neurons/validators/src/services/task_service.py

tweak get dockerhub digest flow

---

neurons/executor/Dockerfile
neurons/executor/Dockerfile.runner
neurons/executor/docker-compose.yml
neurons/executor/pdm.lock
neurons/executor/pyproject.toml
neurons/miners/docker-compose.yml
neurons/validators/.gitignore
neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/docker-compose.yml
neurons/validators/pdm.lock
neurons/validators/pyproject.toml
neurons/validators/src/cli.py
neurons/validators/src/core/validator.py
neurons/validators/src/miner_jobs/machine_scrape.py
neurons/validators/src/miner_jobs/score.py
neurons/validators/src/services/const.py
neurons/validators/src/services/docker_service.py
neurons/validators/src/services/miner_service.py
neurons/validators/src/services/ssh_service.py
neurons/validators/src/services/task_service.py

deploy executor

---

neurons/validators/src/services/task_service.py

- check if docker image digest is empty or not at task_service.py

Hotfix: check-docker-digest-empty

---

datura/datura/requests/miner_requests.py
neurons/executor/.env.template
neurons/executor/Dockerfile
neurons/executor/Dockerfile.runner
neurons/executor/src/core/config.py
neurons/executor/src/services/miner_service.py
neurons/miners/Dockerfile
neurons/miners/Dockerfile.runner
neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/services/miner_service.py
neurons/validators/src/services/task_service.py

feat(validator) - check renting port range

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/services/task_service.py

hot-fix(validator): give 10x score to the rented machines

---

neurons/validators/src/miner_jobs/machine_scrape.py

- md5 checksum for libnvidia-ml.so.1 and nvidia-smi in the machine_scrape

Feature:DAH-766-subnet-validator-md5-checks

---

neurons/validators/src/services/docker_service.py
neurons/validators/src/services/miner_service.py
neurons/validators/src/services/redis_service.py
neurons/validators/src/services/task_service.py
neurons/validators/src/test_validator.py

- store checked ports on redis in synthetic job
- use the stored ports when renting
DAH-767
[Subnet - store checked ports on redis and use those ports when renting](https://www.notion.so/8624050fd1ba4363be433dc457b3aa9b?v=f4338cc3f6424eff8315111a8e24f0e3&p=14cb8bfdbde980199411ea77838c7c0c&pm=s)

store ports on redis

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/core/validator.py
neurons/validators/src/miner_jobs/machine_scrape.py
neurons/validators/src/services/const.py
neurons/validators/src/services/redis_service.py
neurons/validators/src/services/task_service.py

- clear stored available ports from redis when validator starts
- remove ssh_port from the available ports list
- added valid libnvidia so digests list and check in synthetic job
DAH-782
[Subnet - port mapping and libnvidia-ml.so.1 issue](https://www.notion.so/8624050fd1ba4363be433dc457b3aa9b?v=f4338cc3f6424eff8315111a8e24f0e3&p=152b8bfdbde98062ae75d3d29e741337&pm=s)

Fix port map issue and add libnvidia so file digests checking

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/services/task_service.py

hotfix: fix docker port check issue

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/miner_jobs/machine_scrape.py

hotfix: libnvidia-ml.so.1 file path issue

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/miner_jobs/machine_scrape.py

hotfix: fix issue

---

neurons/executor/README.md
neurons/miners/Dockerfile

hotfix: deploy issue on miner

---

neurons/miners/Dockerfile
neurons/miners/pdm.lock
neurons/validators/Dockerfile
neurons/validators/pdm.lock

hotfix: fix deployment issue

---

contrib/CONTRIBUTING.md

This update addresses several small issues in the contributing guidelines, focusing on improving grammar and consistency throughout the document. 
Key changes include:
- Changed "Code Contribution General Guideline" to **"Code Contribution General Guidelines"** to maintain consistency with the rest of the document.
- Updated the table of contents for the **"Suggesting Features"** section to match the full section title, now reading **"Suggesting Enhancements and Features"**.
- Corrected the title **"How Submit A (Good) Feature Suggestion"** to **"How to Submit A (Good) Feature Suggestion"** for grammatical accuracy.
These changes aim to enhance the clarity and readability of the contribution guidelines.

docs: Fix typos, grammar, and consistency issues in CONTRIBUTING.md

---

neurons/validators/src/clients/compute_client.py
neurons/validators/src/services/docker_service.py

- Docker container creation failed when empty volume was passed from backend. 
DAH-827

fix: DAH-827 - sanitize docker volume commands

---

neurons/validators/src/clients/compute_client.py
neurons/validators/src/connector.py
neurons/validators/src/core/utils.py
neurons/validators/src/core/validator.py

- Fix logging issue in validator

fix: format for validators

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/pdm.lock
neurons/validators/pyproject.toml
neurons/validators/src/miner_jobs/machine_scrape.py
neurons/validators/src/services/const.py
neurons/validators/src/services/docker_service.py
neurons/validators/src/services/task_service.py

- update machine scrape and get docker version and digest
- remove docker python lib and use docker cli
DAH-849
[Subnet - Get Docker version and digest](https://www.notion.so/Subnet-Get-Docker-version-and-digest-160b8bfdbde980ecb313c8e1854540a1)

Get docker version and digest

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/services/task_service.py

hotfix: docker connection issue

---

neurons/validators/src/services/const.py

- Add Nvidia H200 into available executors list.

feat: add h200 sxm

---

contrib/STYLE.md

This pull request fixes a typographical error in the `STYLE.md` file. The word "commiting" was corrected to "committing."
- Corrected "commiting" to "committing" in the `STYLE.md` file.
- `STYLE.md`
Correcting typographical errors ensures that the style guide is professional, clear, and easy to understand for all contributors.
- N/A
This fix only involves a documentation update and does not affect the functionality of the code.

Fix typo Update STYLE.md

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/services/docker_service.py

hotfix: update logs in docker_service

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/services/docker_service.py

hotfix: add more logs on renting flow

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/services/task_service.py

hotfix: fix docker connection on the task service

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/miner_jobs/machine_scrape.py

hotfix: add gpu uuid

---

neurons/validators/Dockerfile
neurons/validators/Dockerfile.runner
neurons/validators/src/clients/compute_client.py
neurons/validators/src/payload_models/payloads.py
neurons/validators/src/protocol/vc_protocol/validator_requests.py

check duplicated executors by gpu uuid

---

neurons/executor/.env.template
neurons/executor/Dockerfile
neurons/executor/Dockerfile.runner
neurons/executor/README.md
neurons/executor/src/core/config.py
neurons/executor/src/services/miner_service.py

add SSH_PUBLIC_PORT in executor

---

neurons/validators/src/clients/miner_client.py
neurons/validators/src/core/validator.py
neurons/validators/src/services/task_service.py

- delete set_weights, connection error, connection closed logs

chore: Compress log messages in validator

---

neurons/validators/src/services/task_service.py

The executors that are in progress of rental check should keep as `rented` because if not, validator will clean up the rental containers. But, if executors are in progress of rental check, validator shouldn't give actual score until it pass rental check. 
**Current Issue** is that validator clean up rental containers on executors which are in progress of rental check. So, we need to still return them as "rented" machine from backend, and validator shouldn't give score until it pass rental check.  

fix: stop giving actual score to executors that doesn't pass rental check

---

neurons/validators/src/miner_jobs/score.py

- Hashcat: Disable temperature and fanspeed reads and triggers
- Hashcat: Define specific session name
- Hashcat: fix error

fix issues on hashcat job

---

neurons/validators/src/payload_models/payloads.py
neurons/validators/src/services/docker_service.py

- Accept `shm-size` from backend when create a rental container

feat: add `shm-size` when create a docker container

---

neurons/validators/src/services/const.py

- Add NVIDIA B200
[Subnet/Backend- Add B200 GPU](https://www.notion.so/Subnet-Backend-Add-B200-GPU-1ceb8bfdbde980c6af62f7228feccb54?pvs=23)

feat(validator): DAH-1219 - add NVIDIA B200

---

neurons/validators/src/services/docker_service.py
neurons/validators/src/services/miner_service.py
neurons/validators/src/services/redis_service.py
neurons/validators/src/services/task_service.py

DAH-1220
[Subnet - Rental status mismatch](https://www.notion.so/Subnet-Rental-status-mismatch-1ceb8bfdbde9806a9c9fd5be12ae2755?pvs=23)

fix (validator): DAH-1220 - Rental status mismatch

---

neurons/validators/src/services/interactive_shell_service.py

close interactive shell properly

---

contrib/STYLE.md

Hi there! Jsut fixed some typos, nothing serious

fix: multiple typos of different importance

---

neurons/validators/src/core/config.py
neurons/validators/src/services/task_service.py

-  give 20% of the max score as plus if executor is compatible with DinD

feat: give 20% of the max score as plus

---

neurons/validators/src/services/task_service.py

- Compare previous GPU UUIDs and current GPU UUIDs after sorting 
[Subnet - GPU Changed Issue](https://www.notion.so/Subnet-GPU-Changed-Issue-1e0b8bfdbde980e8b6c4e10d3409034a)

hotfix: DAH-1284 - gpu changed issue

---

neurons/executor/.dockerignore
neurons/executor/nvidia_docker_sysbox_setup.sh

add sysbox 0.6.6 binary on local

---

neurons/executor/README.md

update executor readme for sysbox

---

neurons/validators/src/services/task_service.py

add 5 percent gpu usage space for rented executor

---

neurons/validators/src/services/docker_service.py

- To improve deploying speed, we can skip following checks for official docker images: 
- sshd daemon check
- install sshd
- start sshd
[Subnet - Skip Additional Checks for Official Docker Images](https://www.notion.so/Subnet-Skip-Additional-Checks-for-Official-Docker-Images-21db8bfdbde980fb9246ff2bfc3c4e26)

feat: DAH-1360 -  skip additional checks for official docker images

---

neurons/miners/pdm.lock
neurons/miners/pyproject.toml

fix (miner): build issue -> stick python version to 3.11.11

---

neurons/validators/.env.template
neurons/validators/docker-compose.app.dev.yml
neurons/validators/docker-compose.app.yml
neurons/validators/src/clients/compute_client.py
neurons/validators/src/core/config.py

rebrand celium to lium.io

---

neurons/miners/docker-compose.app.dev.yml
neurons/miners/docker-compose.app.yml
neurons/miners/pdm.lock
neurons/miners/pyproject.toml
neurons/miners/src/clients/miner_portal_client.py
neurons/miners/src/connector.py
neurons/miners/src/core/config.py
neurons/miners/src/protocol/miner_portal_request.py
neurons/miners/src/protocol/miner_request.py
neurons/miners/src/services/executor_service.py
neurons/miners/src/services/ioc.py

- add miner portal connector in miner
- update docker-compose.yml for connector
- executor adding logic from miner portal via ws
[Subnet (miner) - Add miner portal connector](https://www.notion.so/Subnet-miner-Add-miner-portal-connector-24cb8bfdbde980f1b3a6d5344c95adeb?pvs=23)

feat(miner): add miner portal connector

---

neurons/miners/pdm.lock
neurons/validators/pdm.lock

deploy miner

---

neurons/miners/pdm.lock
neurons/miners/pyproject.toml
neurons/validators/pdm.lock
neurons/validators/pyproject.toml

fix(deploy): build issue

---

neurons/miners/src/core/config.py
neurons/validators/src/core/config.py

Remove old contracts in validator and miner.

refactor(miner, validator): remove old collateral contract addresses and versions from settings
